### ISSUE TITLE
Could not pass event CreatureSpawnEvent to NerfPhantoms v1.3.0

### ISSUE THREAD

**Issue by hkkongou** [Tallcraft/NerfPhantoms#13]
![image](https://user-images.githubusercontent.com/61608872/100530622-2d4ffa80-322f-11eb-8cfe-d69ec46a3415.png)
it show the above error log and no phantom is spawned. Config no change.

paper 253 1.16.3 
NerfPhantoms 1.3.0

**Comment by Trikolon** [comment]
Thanks for filing an issue.
This does look like an issue with the config file. Could you please post a copy of the config here? 
You can also try to delete the config file and let the plugin generate a new one.

**Comment by hkkongou** [comment]
I did not edit anything in config file.

```
enabledWorlds:
- world
- world_nether
- world_the_end
- world_main
allowNaturalSpawn: true
onlyNerfNatural: true
muteSound: false
disableAI: false
health: 20.0
damageModifier: 1.0
fixedSize:
  enabled: false
  value: 1
database:
  enabled: false
  type: mysql
  host: localhost
  port: 3306
  name: nerfphantoms
  username: user
  password: '123456'

```
